name: CI/CD Pipeline for train-ticket-reservation  Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and Package WAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Validate with Maven
        run: mvn validate

      - name: Compile with Maven
        run: mvn compile

      - name: Test with Maven
        run: mvn test

      - name: Package with Maven
        run: mvn package

      - name: Verify WAR File
        run: ls -lh target/

      # ✅ Upload WAR artifact so other jobs can use it
      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: train-ticket-reservation-war
          path: target/train-ticket-reservation-6.1.1-SNAPSHOT.war

  deploy-dev:
    name: Deploy to DEV Environment
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download WAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: -war
          path: target/

      - name: Deploy WAR to Tomcat DEV
        run: |
          curl -v -u ${{ secrets.TOMCAT_USER_DEV }}:${{ secrets.TOMCAT_PASS_DEV }} \
          -T target/train-ticket-reservation-6.1.1-SNAPSHOT.war \
          "http://${{ secrets.TOMCAT_URL_DEV }}:8080/manager/text/deploy?path=/trainbook-dev&update=true"

  deploy-test:
    name: Deploy to TEST Environment
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download WAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: train-ticket-reservation-war
          path: target/

      - name: Deploy WAR to Tomcat TEST
        run: |
          curl -v -u ${{ secrets.TOMCAT_USER_TEST }}:${{ secrets.TOMCAT_PASS_TEST }} \
          -T target/train-ticket-reservation-6.1.1-SNAPSHOT.war \
          "http://${{ secrets.TOMCAT_URL_TEST }}:8080/manager/text/deploy?path=/trainbook-test&update=true"

  deploy-preprod:
    name: Deploy to PRE-PROD Environment
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download WAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: train-ticket-reservation-war
          path: target/

      - name: Deploy WAR to Tomcat PRE-PROD
        run: |
          curl -v -u ${{ secrets.TOMCAT_USER_PRE_POD }}:${{ secrets.TOMCAT_PASS_PRE_POD }} \
          -T target/train-ticket-reservation-6.1.1-SNAPSHOT.war \
          "http://${{ secrets.TOMCAT_URL_PRE_POD }}:8080/manager/text/deploy?path=/trainbook-preprod&update=true"

  deploy-prod:
    name: Deploy to PROD Environment
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download WAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: train-ticket-reservation-war
          path: target/

      - name: Deploy WAR to Tomcat PROD
        run: |
          curl -v -u ${{ secrets.TOMCAT_USER_PROD}}:${{ secrets.TOMCAT_PASS_PROD }} \
          -T target/train-ticket-reservation-6.1.1-SNAPSHOT.war \
          "http://${{ secrets.TOMCAT_URL_PROD }}:8080/manager/text/deploy?path=/trainbook-prod&update=true"

